### ISSUE TITLE
'RoutingHTTPServer/RoutingConnection.h' file not found

### ISSUE THREAD

**Issue by LayMuiToh** [facebook/WebDriverAgent#1040]
appium is 1.10.1
When I build WebDriverAgentLib or WebDriverAgentRunner to Generic iOS Device
I got this build error/Users/tohlaymui/Desktop/WebDriverAgent-master/WebDriverAgentLib/Routing/FBWebServer.m:12:9: fatal error: 'RoutingHTTPServer/RoutingConnection.h' file not found
#import <RoutingHTTPServer/RoutingConnection.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by nestamarl** [comment]
#7283
The explanation of "ctrevarthen" worked for me.
In Terminal enter the path of the WebDriverAgent folder eg.
`/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent`
then
`./Scripts/bootstrap.sh -d`

**Comment by LayMuiToh** [comment]
it didn't work, now I got other build errors:
/Users/tohlaymui/.nvm/versions/node/v9.1.0/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Routing/FBWebServer.m:32:41: error: expected identifier or '('
@interface FBHTTPConnection : NSObject  : RoutingConnection
                                        ^
/Users/tohlaymui/.nvm/versions/node/v9.1.0/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Routing/FBWebServer.m:39:76: error: property 'requestURI' not found on object of type 'FBHTTPConnection *'
  [FBLogger logFmt:@"Received request for %@ which we do not handle", self.requestURI];
                                                                           ^
/Users/tohlaymui/.nvm/versions/node/v9.1.0/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Routing/FBWebServer.m:40:10: error: no visible @interface for 'NSObject' declares the selector 'handleResourceNotFound'
  [super handleResourceNotFound];
   ~~~~~ ^~~~~~~~~~~~~~~~~~~~~~
3 errors generated.

**Comment by LayMuiToh** [comment]
issue resolved. thanks

**Comment by zbranzov** [comment]
Same problem appium 1.14.0 . Running the sh script doesn't help

**Comment by MrMarik** [comment]
problem  also , the sh script doesn't help

**Comment by Cprocc** [comment]
> Same problem appium 1.14.0 . Running the sh script doesn't help

can you fix this?

**Comment by Cprocc** [comment]
> problem also , the sh script doesn't help

can you fix this, I got the same  wrong

**Comment by MrMarik** [comment]
> > problem also , the sh script doesn't help
> 
> can you fix this, I got the same wrong

i fixed it, its because i used xcode11-beta, it worked when i used xcode10-release

**Comment by AmulyaKumar1703** [comment]
issue : RoutingHTTPServer/RoutingConnection.h' file not found .   

xcode : 10.2.1 
Appium : 1.13.0 
Device : 12.3.1

i have tried    ./Scripts/bootstrap.sh -d   

still getting same issue . pls help

**Comment by aceESC** [comment]
Try running this codes on the terminal where the webdriveragent folder is.
mkdir -p Resources/WebDriverAgent.bundle
./Scripts/bootstrap.sh -d

**Comment by dtopuzov** [comment]
I think the issue was caused by try to build WDA with old version of Carthage.

This worked for me:
```
cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
rm -rf Carthage
brew uninstall carthage
brew install carthage
sh Scripts/bootstrap.sh -d
```
