### ISSUE TITLE
WebDriver with Appium crashing on click element

### ISSUE THREAD

**Issue by jcavar** [facebook/WebDriverAgent#620]
Hi, we are seeing crash in WebDriverAgent about 70% of time when running our scenarios.

Here is appium log: https://gist.github.com/jcavar/512d9820ceee90cf74437c865d323c54
And here is crash stack trace: https://gist.github.com/jcavar/a30c23b42e98974740accfd49fe42318

**Comment by jcavar** [comment]
It could be related to https://github.com/facebook/WebDriverAgent/issues/584

**Comment by mykola-mokhnach** [comment]
Try to use Appium 1.6.6-beta, which contains the most recent WDA fixes

**Comment by vjmaiky** [comment]
it is still reproducible; tried with 1.6.6. beta 2....

**Comment by vjmaiky** [comment]
it is starting to be annoying...can we somehow workaround it? sometimes i cannot debug a test because of it to fix other failures of the framework...

**Comment by mykola-mokhnach** [comment]
@vjmaiky You can temporarily replace it with click by absolute coordinates as a temporary workaround. This crash happens in XCTest when WDA tries to calculate the element's hitpoint to click on

**Comment by vjmaiky** [comment]
i did that; just basically i identify the element; i get location for width and height and use touch action with press (coordinates) to press on it...for the moment works perfectly

**Comment by jcavar** [comment]
@vjmaiky would you mind sharing your workaround, just to not spend time if you already have it working :)

**Comment by vjmaiky** [comment]
@jcavar @mykola-mokhnach my tentative workaround is still not working every time..but still setup is not crashing so frequently..from 200 test runs i have around 10-20 fails because of it.

			WebElement we = (WebElement) AppiumDriverInstance.getInstance().findElement(By.id(subject));
			int heigt = we.getLocation().getY();
			int width = we.getLocation().getX();
			System.out.println(subject);
			TouchAction touchAction = new TouchAction(AppiumDriverInstance.getInstance()).press(width, heigt).release()
					.perform();

**Comment by jcavar** [comment]
Hmm, ok, that is still quite a lot. For us, we have around 70 scenarios and it usually happens once or twice during full run.

**Comment by marekcirkos** [comment]
@mykola-mokhnach I thought we fixed those? There is try-catch to handle that.

**Comment by mykola-mokhnach** [comment]
@marekcirkos yep, this should be fixed in the recent WDA snapshot, which is included into Appium 1.6.6-beta

**Comment by jcavar** [comment]
I just tried 1.6.6-beta.2 and it is still happening.

**Comment by jcavar** [comment]
I am trying but I am still seeing the same. But I am not sure I see that `try/catch` in code. I see it for `fb_isVisible` but it seems that it is crashing on:
`XCTest                              0x00000001013268e9 -[XCElementSnapshot(Hitpoint) hitPoint]`
I am not sure how that one gets called.

**Comment by marekcirkos** [comment]
Do you got the stack trace? Maybe me are missing some usage.

**Comment by jcavar** [comment]
Yes, it is linked in first comment.

**Comment by jcavar** [comment]
I analysed our failures and it seems like this is happening when we try to click element that has changed recently. I think Appium invalidates element when it changes and we are basically trying to click on invalid element. We already have guard for this situation when we get error from Appium, but in this specific case WebDriver is crashing.

**Comment by jcavar** [comment]
Ok I think exception that is thrown is `NSInvalidArgumentException` which is not for some reason caught by catch block.
https://stackoverflow.com/questions/6412263/nsinvalidargumentexception-not-being-caught-in-code

**Comment by marekcirkos** [comment]
@jcavar This is different issue. We are calling existing method that crashes. IT is weird you are still having this problem. 
Are you sure you are using latest WDA? 
Did you modified WDA's build properties?
