### ISSUE TITLE
Appium - iOS 11 - select_picker_wheel Crash

### ISSUE THREAD

**Issue by Mcfli** [facebook/WebDriverAgent#826]
## The problem
When a UIPicker is shown on screen, clicking any button (Done, Cancel, Confirm) will crash the app if you click it via a command. Clicking it manually does not crash the app, but any command on a device on iOS 11 + 11.1 will crash it. Worked fine on iOS 10.3.

## Environment
Appium version (or git revision) that exhibits the issue: 1.7.1
Last Appium version that did not exhibit the issue (if applicable): N/A
Desktop OS/version used to run Appium: OS X 10.12.6
Node.js version (unless using Appium.app|exe): 7.10.0
Mobile platform/version under test: iOS 11, 11.1, 10.3
Real device or emulator/simulator: Simulator
Appium CLI or Appium.app|exe: Appium CLI

## Details
Posted this on Appium issues, was sent here for help.

## Link to Appium logs
[Appium Log](https://gist.github.com/Mcfli/e0d0c41040a467ff6597b0775b003971)
[iOS Crash Log](https://gist.github.com/Mcfli/87a176c907c6cb4fded1924eee3fe66d)

## Code To Reproduce Issue
Ran this during appium ruby console (arc):
`wheel = find_element(:class, 'XCUIElementTypePickerWheel')`
`select_picker_wheel(element:wheel, order:'next', offset:0.15)`
`id('Confirm').click`

**Comment by imalyar** [comment]
occurred for me to

**Comment by tommirit** [comment]
Reproduces for me too.
Seems that picker will crash the app if there are lots of items in picker.
For example 400 items in picker crashed the app but 20 didn't.
Made also issue to appium (https://github.com/appium/appium/issues/9903)  and they asked to create an issue here.
Should I make new issue or is this one enough?

**Comment by alangithubtrader** [comment]
This is happening to me too. Any updates on this?

**Comment by GrzegorzSidwa** [comment]
Issue described here suggest that it's related to popovers (with buttons) than with pickers itself. I've described it with details on appium project: https://github.com/appium/appium/issues/10029. It's related to picker itself (even if it's only simple UIPickerView). Number of rows on which it's workin/crushing depends on the device. I got on my application under test situation that for 10 values it was not working and for 5 it did. In the sample app which I've prepared for investigation purpose it was that for 20elements on picker it works and for 30 it didn't. It's something what @tommirit  has mentioned. In my case it was similar setup like for @alangithubtrader  - Appium 1.7.1/1.7.2, .Net Driver 3.0.0.2 and iOS 11.x.

**Comment by alangithubtrader** [comment]
@GrzegorzSidwa 

Thanks for investigating the problem and thanks for sharing your results with us!

Has anyone found a work around for this problem?  Our pass rate on our entire iOS regression suite has suffered due to this single issue.

**Comment by PaulinkaS** [comment]
I am experiencing the same issue while using .Net driver 3.0.0.2, Appium 1.7.2 and iOS 11.1. I could recreate also the issue described by @GrzegorzSidwa . 
Is there any known workaround or solution to this problem? It would be extremely helpful to get some help with this since it is blocking any further work for newer iOS versions on my side.

**Comment by SivarajanMano** [comment]
Hi All,

I am facing the same issue with following environment IOS 11.2.5, Appium 1.7.2. 

Is their any workaround has been identified?

**Comment by marcaractac** [comment]
I am also facing the same issue with iOS 11.2.5, Appium v1.7.2. Has anyone found a workaround?

**Comment by Corji** [comment]
Im facing the same issue with IOS 11.2.5 and Appium 1.7.2.

**Comment by Supahfly84** [comment]
Same behavior here. Started with iOS version 11.1

**Comment by marekcirkos** [comment]
This is bug in UIAccessibility framework, you should file separate bug reports with Apple to give them strong signal on this. There is not much we can do on WDA side.

**Comment by rkrdpm** [comment]
This seems to have resolved.

**Comment by Corji** [comment]
Probably, how do you got the update into appium?

**Comment by rkrdpm** [comment]
i am seeing this issue in iOS Simulator 11.2 with Appium 1.7.2. Anyone else facing this issue?

**Comment by melleth-marcelo-bcs** [comment]
+1 same issue, has anyone found a workaround? Thanks.

**Comment by sumanthmattapalli** [comment]
Fixed on Appium v1.8.0 ( 1.6.1)

**Comment by tanmoysahat** [comment]
m facing the same issue with iOS 11.2.2 and appium 1.7.2. any one found the root cause of the issue.
@sumanthmattapalli does that issue completely resolved with appium 1.8.0.Did you find the reason for the crash. i mean is it from iOS side or appium side.

**Comment by xmaska** [comment]
Same issue here, with the following configuration:
Emulated Iphone X running iOS 11.2
Appium 6.1.0 (as npm module)

Application just crashes when I try to locate one of the XCUIElementTypePickerWheels from a date selector using appium inspector.
When running the test with io.appium java (6.1.0) crash happens when I try to move the picker the second time. 

Code:
@iOSXCUITFindBy(xpath = "//XCUIElementTypePickerWheel[@value=\"Month\"]")
MobileElement dobMonthElement;

@iOSXCUITFindBy(xpath = "//XCUIElementTypePickerWheel[@value=\"Year\"]")
MobileElement dobYearElement;

pickerNext(dobMonthElement);
pickerNext(dobMonthElement);

where pickerNext:
public void pickerNext(MobileElement element){
        JavascriptExecutor js = (JavascriptExecutor) driver;
        Map<String, Object> params = new HashMap<>();
        params.put("order", "next");
        params.put("offset", 0.15);
        params.put("element", element.getId());
        js.executeScript("mobile: selectPickerWheelValue", params);
    }

This problem is clearly a blocker from my project point of view. :(

**Comment by Mcfli** [comment]
For people saying this has resolved, this is very much still a problem. I've run this on Appium 1.8.1 and iOS 11.2 and it's still crashing with the same original issue.

**Comment by mikedouglasdev** [comment]
We are also running into this issue where it crashes on the date picker.  Can this be re-opened?  Is there any workaround without changing the code?

**Comment by Joshua-Casera-ConnectedLab** [comment]
I've forgotten about this thread for a while, but my team did find a work around. We just send the keys we are looking for into the picker wheel and it will navigate to the right entry automatically. Its a bit rough when there are other symbols (like images or weird unicode), but it works. Not sure if it works for date pickers, since we haven't had to automate any of those for our work. Hopefully this helps some of you.

**Comment by marcaractac** [comment]
Yeah sending the keys is also what I ended up doing after as well.

**Comment by robbnic** [comment]
You all can send keys? The app crashes for us just on doing a search. You cannot use appium on a page with a picker at all.

**Comment by iammike** [comment]
Also having this issue. App most often crashes when clicking the 'OK' button. Have had to wrap near every line of code in "Are you still there? If not, reset and try again." As soon as I plug one hole, another pops up. 

Appium 1.7.2, iOS 11.1.

**Comment by sansquer** [comment]
Same issue for me. The app freezes for at least 2 minutes and then restarts.

running Appium 1.10.0, iOS 12.1 (tried and several phones)

**Comment by PraveenKumarQA** [comment]
Hi, I may be late to the party but I was able to get around the problem using iOS - 11.4, Appium - 1.11.0-beta.3, node - v10.14.2

**Comment by Thejdeepreddyputtaparthi** [comment]
any solution  for this @sansquer @marcaractac @tommirit @Mcfli @imalyar @tommirit
